openapi: 3.0.3
info:
  title: Bubbly
  description: |-
    Bubbly adalah aplikasi platform untuk mahasiswa Universitas Sam Ratulangi untuk menawarkan produk dan jasa yang mereka miliki kepada masyarakat luas khususnya di Manado.
  version: 1.0.0
servers:
- url: https://example.com/
tags:
- name: Auth
  description: Melakukan autentikasi
- name: Admin
  description: Menampilkan dan mengelola data-data yang berhubungan dengan fitur-fitur yang dapat dilakukan oleh admin.
- name: Product
  description: Menampilkan dan mengelola data-data yang berhubungan dengan data-data produk yang ada.
- name: Categories
  description: Menampilkan dan mengelola data-data yang berhubungan dengan data-data kategori produk.
- name: Store
  description: Menampilkan dan mengelola data-data yang berhubungan dengan data toko penjual.
paths:
  /auth/login:
    post:
      tags:
      - Auth
      summary: Melakukan login
      description: Melakukan login menggunakan kredensial yang diperlukan yaitu NIS untuk siswa/i atau NIP untuk non-siswa/i
      operationId: postLogin
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Berhasil login !
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Login berhasil !
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrLWVuZC1idWJibHkiLCJhdWQiOiJmcm9udC1lbmQtYnViYmx5IiwiaWF0IjoxNzE3NjU2ODQyLCJleHAiOjE3MTc2NjA0NDIsInN1YiI6IjQ1NzQzNzMwLThlNDEtNDRjYi1iY2MwLWM4NjdhYjI5YmVkNSIsImVtYWlsIjoiYnV5ZXIxQGV4YW1wbGUuY29tIiwicm9sZV9pZCI6IjkxYjk2NDUyLTBhNTQtNGZmNi1hZmJkLThjOTA2YWVjMmJkMSJ9.Iiz9RM-YOlG67bqYCAUE29rF7BjrW1IlOX54vQ982rZabU20SH18_ktoQizr3SMZSg-8C9mjdF7OHcSNblTzSftkARiDCpZIAjRFfk6xdA2yTgckeKIqgs_Yt-dA8pLV5FRo2tUP8c0J669XfXcWclQxyWA32Fdsi-EcBH_ccftl1VQVehsx5TRWBp3DWGVKg6PComgM3uFxNFzgJSJGb5_Sa4h8Zi92T5SQJmsqj73WaWT-l0EU_RMw7GSor4EZSiDfYdhfnxq0q_Hr7QAAVdbbDuCNh-ulGqrqkS-Iffls6PcMuLWERWBHQZktS5LTnZtMuywUfq4u8uUQYu0lNA"
                      refresh_token:
                        type: string
                        example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrLWVuZC1idWJibHkiLCJhdWQiOiJmcm9udC1lbmQtYnViYmx5IiwiaWF0IjoxNzE3NjU2ODQyLCJleHAiOjE3MTg4NjY0NDIsInN1YiI6IjQ1NzQzNzMwLThlNDEtNDRjYi1iY2MwLWM4NjdhYjI5YmVkNSJ9.Z4aMm3KiuE_zy1WDfSaUpdtLF4ltCWSVjvW099kh2xTbXiz-6z4F9lZOBttxzywkP_C4Eqf5v_G9Q-1PT96qggCE6y9xyCP9yfOdmTaewRn1pW8cgEimSCz1RUdcb8J-UmeGR_yc4jmRexkESHtu-lNhzCCw0I7qcrmwqqvmKvch9MjmVxpSQYusfi_wS0v3FBb1_cddstfogfFXxdNrGYnu8pjNFsrcCqlnlnaUkYBn7E1BGI_BuIvzK93YzCB3wV24-0id4_XwFyVmXMw9OBWKhBEP1UShCwd5z5L41MxgXcgFsZexTE5fHYGLlzT_28nQxdrB8T0TSkSLSmIi-g"
        '400':
          description: Jika email atau password yang diberikan tidak benar
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: Email atau password salah !
                  data:
                    example: null
        '401':
          $ref: '#/components/responses/InvalidToken'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /auth/refresh-token:
    post:
      tags:
      - Auth
      summary: Mendapatkan access token yang baru
      description: Mendapatkan access token dan refresh token baru menggunakan refresh token yang didapatkan saat melakukan login sebelumnya.
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJiYWNrLWVuZC1idWJibHkiLCJhdWQiOiJmcm9udC1lbmQtYnViYmx5IiwiaWF0IjoxNzE3NjU3MzA4LCJleHAiOjE3MTg4NjY5MDgsInN1YiI6IjQ1NzQzNzMwLThlNDEtNDRjYi1iY2MwLWM4NjdhYjI5YmVkNSJ9.Vtnq42rrxPvtOnGyKp5D4V9zGqO7gcA1iQqvHNiyYgnpeM0OEJKMNQbpGHGTgiAJOQhSJfWDIInNj6Qr117MWF9vW_eAFbCtGVSxYFVTaB7MPP7YuMNgW4GV9tAmBj2aSaf0ddDVYBGGtr-un6c9EKXvosbCdT1qH96FhsP37YnNl9KVUdt_ZFAGZrcl5ntql1yQI4oAKtr_jAomO0W1iFd_0cKJnWHWnwBr_bkabndaZn2XQGV4h8hrqVwq5GMhFX77I80TYNCD-MOoXe2vdD_SRdxFQylE-4LXlSduyU7qTq5Iofv1UtQ-Kaf4ePHVUeE207VRrcGJwI1qXZR8lQ"
      responses:
        '200':
          description: Berhasil mendapatkan access token dan refresh token baru
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Berhasil mendapatkan access token dan refresh token yang baru !
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                      refresh_token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /products:
    get:
      tags:
      - Product
      summary: Mendapatkan daftar data dari semua produk yang ada.
      description: Mendapatkan daftar data-data dari semua produk yang ada.
      parameters:
      - name: category
        in: query
        description: Id kategori produk
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Berhasil mendapatkan daftar produk.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Berhasil mendapatkan daftar produk
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "28a77955-c1b9-4bfd-b0d0-6a4c5366a3f9"
                        product_name:
                          type: string
                          example: "Product 1 in Electronics"
                        price:
                          type: number
                          example: 10000
                        description:
                          type: string
                          example: "Description for Product 1 in Electronics"
                        category:
                          type: string
                          example: "Electronics"
                        likes:
                          type: integer
                          example: 10
                        store_name:
                          type: string
                          example: "Cassie Bakery"
                        image:
                          type: string
                          example: ""
                    example:
                    - id: "28a77955-c1b9-4bfd-b0d0-6a4c5366a3f9"
                      product_name: "Product 1 in Electronics"
                      price: "10000"
                      description: "Description for Product 1 in Electronics"
                      category: "Electronics"
                      likes: 10
                      store_name: "Cassie Bakery"
                      image: ""
                    - id: "2062a5ee-0b60-46ec-856b-f80dc0fb3361"
                      product_name: "Product 2 in Electronics"
                      price: "20000"
                      description: "Description for Product 2 in Electronics"
                      category: "Electronics"
                      likes: 20
                      store_name: "Cassie Bakery"
                      image: ""
                    - id: "834c3334-f46e-4b39-8ef3-dcf05486c392"
                      product_name: "Product 3 in Electronics"
                      price: "30000"
                      description: "Description for Product 3 in Electronics"
                      category: "Electronics"
                      likes: 30
                      store_name: "Cassie Bakery"
                      image: ""
                    - id: "93c3df72-c2ea-49a4-8f51-2d4c524b045d"
                      product_name: "Product 1 in Electronics"
                      price: "10000"
                      description: "Description for Product 1 in Electronics"
                      category: "Electronics"
                      likes: 10
                      store_name: "Viels Design Studio"
                      image: ""
                    - id: "f6913d78-13e2-42dd-946a-30f5f3648dc6"
                      product_name: "Product 2 in Electronics"
                      price: "20000"
                      description: "Description for Product 2 in Electronics"
                      category: "Electronics"
                      likes: 20
                      store_name: "Viels Design Studio"
                      image: ""
                    - id: "dca0cbab-5674-49fb-900b-004e23c41f8f"
                      product_name: "Product 3 in Electronics"
                      price: "30000"
                      description: "Description for Product 3 in Electronics"
                      category: "Electronics"
                      likes: 30
                      store_name: "Viels Design Studio"
                      image: ""
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /categories:
    get:
      tags:
      - Categories
      summary: Mendapatkan daftar kategori produk
      description: Mendapatkan daftar semua kategori produk yang tersedia
      responses:
        '200':
          description: Berhasil mendapatkan daftar kategori produk
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Berhasil mendapatkan daftar kategori produk
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "3cf967ca-e8b5-4aad-b8dc-5d2c41f515df"
                        nama_kategori:
                          type: string
                          example: "Electronics"
                      example:
                      - id: "3cf967ca-e8b5-4aad-b8dc-5d2c41f515df"
                        nama_kategori: "Electronics"
                      - id: "8b675157-a597-4830-8d23-65d6ed5451cb"
                        nama_kategori: "Clothing"
                      - id: "3f26342a-35d7-470f-9145-1b671ab8f3c3"
                        nama_kategori: "Books"

        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /product/{id_product}:
    get:
      tags:
      - Product
      summary: Mendapatkan data produk berdasarkan ID
      description: Mendapatkan detail produk berdasarkan ID produk yang diberikan
      operationId: getProductById
      parameters:
      - name: id_product
        in: path
        description: ID produk yang ingin diperoleh informasinya
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Berhasil mendapatkan data produk
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Berhasil mendapatkan data produk
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "599c9090-5abb-437e-9359-4c332c24b857"
                      name:
                        type: string
                        example: Product 1 in Electronics
                      price:
                        type: integer
                        example: 10000
                      store_name:
                        type: string
                        example: Cassie Bakery
                      image_url:
                        type: string
                        example: ""
                      contact:
                        type: string
                        example: "081229941540"
                      product_description:
                        type: string
                        example: Description for Product 1 in Electronics
                      store_description:
                        type: string
                        example: Toko kue terbaik
                      google_maps_src:
                        type: string
                        example: null
        '404':
          description: Produk tidak ditemukan
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: Produk tidak ditemukan
                  data:
                    example: null
        '500':
          $ref: '#/components/responses/InternalServerError'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    InvalidToken:
      description: Token tidak valid
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              message:
                type: string
                example: Token tidak valid
              data:
                example: null
    MethodNotAllowed:
      description: Method yang digunakan tidak sesuai
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 405
              message:
                type: string
                example: HTTP method tidak sesuai
              data:
                example: null
    InternalServerError:
      description: Kesalahan pada Server
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              message:
                type: string
                example: Kesalahan pada server
              data:
                example: null
    NotFound:
      description: Data tidak ditemukan
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 404
              message:
                type: string
                example: Not Found
              data:
                example: null
